import { type NextPage } from "next";
import Head from "next/head";

import { api } from "~/utils/api";
import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";

const Home: NextPage = () => {
  const { data } = api.product.getAll.useQuery();
  const user = useUser();

  console.log(data);
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="text-white">
          {!user.isSignedIn ? (
            <SignInButton>Sign in with Clerk</SignInButton>
          ) : (
            <SignOutButton />
          )}
        </div>

        <div>
          <h1 className="text-4xl font-bold">Products</h1>
          <div>
            {data?.map((product) => (
              <div key={product.id}>
                <h2>{product.name}</h2>
                <p>{product.description}</p>
              </div>
            ))}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
